### ISSUE TITLE
feat: trailingSlash flag

### ISSUE THREAD

**Issue by pegaltier** [d-koppenhagen/scully-plugin-toc#5]
I have enabled the plugin seoHrefOptimise and the plugin toc but the generated toc links doesn't contains the trailing slash so it's not perfect seo wise.

Similar issue to:
- https://github.com/gammastream/scully-plugins/issues/11
- https://github.com/gammastream/scully-plugins/commit/f8563792f005900957467880ad34cd126b47a1fa

**Comment by d-koppenhagen** [comment]
Hey, thanks for reporting.

Unfortunately I am not that much into SEO optimisation. Can give me a concrete example whats generated currently and what do you expect to be generated?

**Comment by pegaltier** [comment]
Thank for replying @d-koppenhagen Actually it's very straightforward :
- Current TOC anchor:<a href="/path#mytitle">My title</a>
- Expected TOC anchor:<a href="/path/#mytitle">My title</a>

**Comment by d-koppenhagen** [comment]
it has been released with version 1.2.0
